// Typed access to the Wails-injected globals (window.go.main.App for bound Go
// methods, window.runtime for events). The committed app does NOT import the
// generated frontend/wailsjs/ bindings (that folder is gitignored and only
// regenerated by `wails dev`/`wails build`), so the frontend builds standalone
// with `bun run build` while Wails still injects these globals at runtime.

import type { Album, FirstMetadata, RunRequest } from './types';

interface AppBinding {
  DefaultRequest(): Promise<RunRequest>;
  Run(req: RunRequest): Promise<void>;
  Cancel(): Promise<void>;
  IsRunning(): Promise<boolean>;
  OpenFolder(): Promise<string>;
  InitialFolder(): Promise<string>;
  ReadFirstMetadata(dir: string): Promise<FirstMetadata>;
  ReadLibrary(dir: string, recursive: boolean): Promise<Album[]>;
}

interface WailsRuntime {
  EventsOn(name: string, cb: (...args: unknown[]) => void): void;
  EventsOff(name: string): void;
}

declare global {
  interface Window {
    go?: { main?: { App?: AppBinding } };
    runtime?: WailsRuntime;
  }
}

/** The bound Go methods, or undefined before Wails has injected them. */
export function app(): AppBinding | undefined {
  return window.go?.main?.App;
}

/** The Wails runtime (events), or undefined before injection. */
export function runtime(): WailsRuntime | undefined {
  return window.runtime;
}

/** True once both the bindings and the runtime are present. */
export function wailsReady(): boolean {
  return !!app() && !!runtime();
}

/** Resolve once Wails has injected its globals, or reject after a timeout. */
export async function waitForWails(timeoutMs = 5000): Promise<boolean> {
  const t0 = Date.now();
  while (!wailsReady()) {
    if (Date.now() - t0 > timeoutMs) return false;
    await new Promise((r) => setTimeout(r, 50));
  }
  return true;
}

/** cf:* event names emitted by internal/ui.Controller (and cf:folder by app.go). */
export const Events = {
  Progress: 'cf:progress',
  Done: 'cf:done',
  Error: 'cf:error',
  State: 'cf:state',
  Folder: 'cf:folder',
} as const;
